# Generated by Django 5.2.10 on 2026-01-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='problem',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solutions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('BEG', 'Beginner'), ('INT', 'Intermediate'), ('ADV', 'Advanced'), ('PRO', 'Pro')], max_length=3),
        ),
        migrations.AlterField(
            model_name='problem',
            name='real_life_context',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
